/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsCharts: typeof import('./src/components/AnalyticsCharts.vue')['default']
    ArticleCarousel: typeof import('./src/components/ArticleCarousel.vue')['default']
    ArticleEditor: typeof import('./src/components/ArticleEditor.vue')['default']
    ArticleToc: typeof import('./src/components/ArticleToc.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable.vue')['default']
    BlogLayout: typeof import('./src/components/BlogLayout.vue')['default']
    CommentSection: typeof import('./src/components/CommentSection.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    LayoutFooter: typeof import('./src/components/LayoutFooter.vue')['default']
    LayoutHead: typeof import('./src/components/LayoutHead.vue')['default']
    LoadFailed: typeof import('./src/components/LoadFailed.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    RagChatWidget: typeof import('./src/components/RagChatWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortFilter: typeof import('./src/components/SortFilter.vue')['default']
    TagChart: typeof import('./src/components/TagChart.vue')['default']
    TagFilter: typeof import('./src/components/TagFilter.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
